version: "2"

services:



#### #### ####
#  application server
#### #### ####

    php:
        image: php:7.1.3-fpm-alpine
        volumes_from:
            - storage
        ports:
            - "9000:9000"
        expose:
            - 9000
        links:
            - mariadb

    hhvm:
        image: diegomarangoni/hhvm:fastcgi
        volumes_from:
            - storage
        ports:
            - "9000:9000"
        expose:
            - 9000
        links:
            - mariadb



#### #### ####
#  web server (h2o)
#### #### ####

    h2oweb-php:
        image: lkwg82/h2o-http2-server:v2.2.0
        volumes_from:
            - storage
        ports:
            - "80:80"
            - "443:443"
        expose:
            - 80
            - 443
        links:
            - php

    h2oweb-hhvm:
        image: lkwg82/h2o-http2-server:v2.2.0
        volumes_from:
            - storage
        ports:
            - "80:80"
            - "443:443"
        expose:
            - 80
            - 443
        links:
            - hhvm



#### #### ####
#  web server (nginx)
#### #### ####

    nginx-php:
        image: nginx:1.11.13-alpine
        volumes_from:
            - storage
        ports:
            - "80:80"
            - "443:443"
        expose:
            - 80
            - 443
        links:
            - php

    nginx-hhvm:
        image: nginx:1.11.13-alpine
        volumes_from:
            - storage
        ports:
            - "80:80"
            - "443:443"
        expose:
            - 80
            - 443
        links:
            - hhvm



#### #### ####
#  database server
#### #### ####

    mariadb:
        image: mariadb:10.1.22
        volumes_from:
            - storage
        environment:
            MYSQL_DATABASE: mariadb_database
            MYSQL_USER: mariadb_default_user
            MYSQL_PASSWORD: mariadb_default_password
            MYSQL_ROOT_PASSWORD: mariadb_root_password



#### #### ####
#  storage server
#### #### ####

    storage:
        image: busybox
        tty: true
        volumes:
            - ./storage/etc/h2o/h2o.conf:/etc/h2o/h2o.conf:ro
            - ./storage/etc/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./storage/var/www:/var/www
